[general]
id = "sd2-ff00_0_210"
config_dir = "gen/ASff00_0_210"

[trust_db]
connection = "gen-cache/sd2-ff00_0_210.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_210.path.db"

[sd]
address = "10.0.0.166:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.166:30455"

[features]

[api]
addr = "10.0.0.166:30955"

[drkey_level2_db]
connection = "gen-cache/sd2-ff00_0_210.drkey_level2.db"

[log.console]
level = "debug"
