[general]
id = "sd1-ff00_0_131"
config_dir = "gen/ASff00_0_131"

[trust_db]
connection = "gen-cache/sd1-ff00_0_131.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_131.path.db"

[sd]
address = "10.0.0.133:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.133:30455"

[features]

[api]
addr = "10.0.0.133:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-ff00_0_131.drkey_level2.db"

[log.console]
level = "debug"
