[general]
id = "cs2-ff00_0_220-1"
config_dir = "gen/ASff00_0_220"

[trust_db]
connection = "gen-cache/cs2-ff00_0_220-1.trust.db"

[beacon_db]
connection = "gen-cache/cs2-ff00_0_220-1.beacon.db"

[path_db]
connection = "gen-cache/cs2-ff00_0_220-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.197:30452"

[api]
addr = "10.0.0.197:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "debug"

[drkey.level1_db]
connection = "gen-cache/cs2-ff00_0_220-1.drkey_level1.db"

[drkey.secret_value_db]
connection = "gen-cache/cs2-ff00_0_220-1.secret_value.db"
