local_address = "1-ff00:0:110,192.168.1.34:10123"
daemon_address = "127.0.0.1:30255"

mbg_reference_clocks = ["/dev/mbgclock0"]

ntske_cert_file = "gen/tls.crt"
ntske_key_file = "gen/tls.key"
ntske_server_name = "localhost"
