name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HAS_CHRONY: True
    steps:
      - uses: actions/checkout@v3     

      - name: Install Chrony
        run: |
          sudo apt-get install libgnutls28-dev
          sudo apt-get install gnutls-bin
          sudo apt-get install libtomcrypt-dev
          sudo apt-get install nettle-dev
          curl -LO https://download.tuxfamily.org/chrony/chrony-4.3.tar.gz
          tar -xzvf chrony-4.3.tar.gz 
          mv chrony-4.3 chrony-4.3-src
          mkdir chrony-4.3
          cd chrony-4.3-src/
          ./configure --prefix=/home/ubuntu/chrony-4.3
          make
          sudo make install
      
      - name: Start Chrony
        run: |
          sh testnet/tls-gen-cert.sh
          sudo systemctl stop chronyd
          sudo /home/ubuntu/chrony-4.3/sbin/chronyd -4 -f /home/runner/work/scion-time/scion-time/testnet/chrony/chronyNTS.conf

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -o bin/timeservice timeservice.go timeservicex.go

      - name: Test
        run: go test